export declare const HamburgerTypes: {
    "3dx": "3dx";
    "3dx-r": "3dx-r";
    "3dy": "3dy";
    "3dy-r": "3dy-r";
    "3dxy": "3dxy";
    "3dxy-r": "3dxy-r";
    arrow: "arrow";
    "arrow-r": "arrow-r";
    arrowalt: "arrowalt";
    "arrowalt-r": "arrowalt-r";
    arrowturn: "arrowturn";
    "arrowturn-r": "arrowturn-r";
    boring: "boring";
    collapse: "collapse";
    "collapse-r": "collapse-r";
    elastic: "elastic";
    "elastic-r": "elastic-r";
    emphatic: "emphatic";
    "emphatic-r": "emphatic-r";
    minus: "minus";
    slider: "slider";
    "slider-r": "slider-r";
    spin: "spin";
    "spin-r": "spin-r";
    spring: "spring";
    "spring-r": "spring-r";
    stand: "stand";
    "stand-r": "stand-r";
    squeeze: "squeeze";
    vortex: "vortex";
    "vortex-r": "vortex-r";
};
export declare type HamburgerTypes = keyof typeof HamburgerTypes;
